# Generated by Django 4.0.5 on 2022-07-19 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoFinalApp', '0003_persona'),
    ]

    operations = [
        migrations.DeleteModel(
            name='persona',
        ),
    ]
